apiVersion: apps/v1
kind: Deployment
metadata:
  name: matcher
  namespace: redpanda
spec:
  selector:
    matchLabels:
      app: matcher
  template:
    metadata:
      labels:
        app: matcher
    spec:
      containers:
      - name: matcher
        image: ghcr.io/k8sstormcenter/matcher:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"