apiVersion: v1
kind: Pod
metadata:
  name: matcher
  namespace: redpanda
spec:
  containers:
    - name: example-container
      image: jtaha/test:latest
      # command: ["python", "src/patternmatcher/main.py"]
      # args: ["--neo_uri", "bolt://neo4j-poc.neo4j.svc.cluster.local:7687", "--neo_user", "neo4j", "--neo_pass", "password", "--kafka_uri", "redpanda-src.redpanda.svc.cluster.local:9093", "--kafka_topic", "cr1"]
